name: Bug report
description: Report a bug or regression
labels: ["bug"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you expect to happen, and what actually happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Steps to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs (redact secrets).
      render: shell
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Commit / tag
      description: If known, provide the commit SHA or release tag.
    validations:
      required: false

