"""Domain ports for the context."""

from src.domain.tasks.ports import (
    TaskOperationsPort,
    TaskOrchestratorPort,
    TaskObserverPort,
    TaskPlannerPort,
    TaskPlanStorePort,
    PlanningIntentPort,
    FastPathPlannerPort,
    AutomationSchedulerPort,
    PlanCancellationPort,
    PlanningEventBusPort,
    TaskPlanningStorePort,
    TaskQueryPort,
    TaskPersistencePort,
    TaskStatusTransitionPort,
    TaskExecutionTreePort,
    TaskExecutionEventBusPort,
    TaskExecutionEventStreamPort,
    TaskExecutionEventSubscription,
    TaskSchedulerPort,
    TaskConversationPort,
    PreferenceLearningPort,
)
from src.domain.tasks.planning_models import (
    PlanningIntent,
    ScheduleSpec,
    DataQuery,
    FastPathResult,
    IntentType,
    is_fast_path_eligible,
    compute_date_range,
)
from src.domain.tasks.models import (
    ApprovalType,
    CheckpointConfig,
    ObserverProposal,
    ReplanContext,
    Task,
    TaskException,
    TaskStatus,
    TaskStep,
)
from src.domain.tasks.planning_helpers import assign_parallel_groups
from src.domain.tasks.risk_detector import RiskDetectorService, RiskAssessment, RiskLevel
from src.domain.tasks.errors import InvalidTransitionError

__all__ = [
    "TaskOperationsPort",
    "TaskOrchestratorPort",
    "TaskObserverPort",
    "TaskPlannerPort",
    "TaskPlanStorePort",
    "PlanningIntentPort",
    "FastPathPlannerPort",
    "AutomationSchedulerPort",
    "PlanCancellationPort",
    "PlanningEventBusPort",
    "TaskPlanningStorePort",
    "TaskQueryPort",
    "TaskPersistencePort",
    "TaskStatusTransitionPort",
    "TaskExecutionTreePort",
    "TaskExecutionEventBusPort",
    "TaskExecutionEventStreamPort",
    "TaskExecutionEventSubscription",
    "TaskSchedulerPort",
    "TaskConversationPort",
    "PreferenceLearningPort",
    "PlanningIntent",
    "ScheduleSpec",
    "DataQuery",
    "FastPathResult",
    "IntentType",
    "is_fast_path_eligible",
    "compute_date_range",
    "assign_parallel_groups",
    "RiskDetectorService",
    "RiskAssessment",
    "RiskLevel",
    "InvalidTransitionError",
    "ApprovalType",
    "CheckpointConfig",
    "ObserverProposal",
    "ReplanContext",
    "Task",
    "TaskException",
    "TaskStatus",
    "TaskStep",
]
