"""add_workflow_orchestration_metadata

Revision ID: c43797c75e38
Revises: 5fa6f1679964
Create Date: 2025-11-11 17:54:50.784502

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c43797c75e38"
down_revision = "5fa6f1679964"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_specs", sa.Column("metadata", sa.JSON(), nullable=True))
    op.add_column(
        "workflow_specs", sa.Column("pattern_type", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "workflow_specs", sa.Column("category", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "workflow_specs", sa.Column("reusability_score", sa.Integer(), nullable=True)
    )
    # Add columns as nullable first to avoid constraint violations
    op.add_column(
        "workflow_specs", sa.Column("total_runs", sa.Integer(), nullable=True)
    )
    op.add_column(
        "workflow_specs", sa.Column("successful_runs", sa.Integer(), nullable=True)
    )
    op.add_column(
        "workflow_specs", sa.Column("failed_runs", sa.Integer(), nullable=True)
    )
    op.add_column(
        "workflow_specs",
        sa.Column("avg_execution_time_ms", sa.Integer(), nullable=True),
    )
    op.add_column(
        "workflow_specs", sa.Column("last_run_at", sa.DateTime(), nullable=True)
    )

    # Ensure new metric columns have defaults for existing rows before enforcing NOT NULL
    # Safe for empty tables: UPDATE with WHERE clause returns 0 rows updated if table is empty
    op.execute("UPDATE workflow_specs SET total_runs = 0 WHERE total_runs IS NULL")
    op.execute("UPDATE workflow_specs SET successful_runs = 0 WHERE successful_runs IS NULL")
    op.execute("UPDATE workflow_specs SET failed_runs = 0 WHERE failed_runs IS NULL")

    op.alter_column("workflow_specs", "total_runs", nullable=False)
    op.alter_column("workflow_specs", "successful_runs", nullable=False)
    op.alter_column("workflow_specs", "failed_runs", nullable=False)

    op.create_index(
        "idx_wf_spec_category", "workflow_specs", ["category"], unique=False
    )
    op.create_index(
        "idx_wf_spec_last_run", "workflow_specs", ["last_run_at"], unique=False
    )
    op.create_index(
        "idx_wf_spec_pattern_type", "workflow_specs", ["pattern_type"], unique=False
    )
    op.create_index(
        "idx_wf_spec_reusability", "workflow_specs", ["reusability_score"], unique=False
    )
    op.create_index(
        "idx_wf_spec_total_runs", "workflow_specs", ["total_runs"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_wf_spec_total_runs", table_name="workflow_specs")
    op.drop_index("idx_wf_spec_reusability", table_name="workflow_specs")
    op.drop_index("idx_wf_spec_pattern_type", table_name="workflow_specs")
    op.drop_index("idx_wf_spec_last_run", table_name="workflow_specs")
    op.drop_index("idx_wf_spec_category", table_name="workflow_specs")
    op.drop_column("workflow_specs", "last_run_at")
    op.drop_column("workflow_specs", "avg_execution_time_ms")
    op.drop_column("workflow_specs", "failed_runs")
    op.drop_column("workflow_specs", "successful_runs")
    op.drop_column("workflow_specs", "total_runs")
    op.drop_column("workflow_specs", "reusability_score")
    op.drop_column("workflow_specs", "category")
    op.drop_column("workflow_specs", "pattern_type")
    op.drop_column("workflow_specs", "metadata")
    # ### end Alembic commands ###
